spring.application.name=trace-query-service
server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/tracenet_trace_db
spring.datasource.username=ivanbhargava
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true