spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/tracenet_auth_db
spring.datasource.username=ivanbhargava
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=traceNetSuperSecretKeyForDevelopmentOnlyChangeLater123456789
jwt.expiration-ms=86400000