spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[1].id=trace-ingestion-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/traces/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[2].id=trace-query-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/query/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1

management.endpoints.web.exposure.include=health,info

jwt.secret=traceNetSuperSecretKeyForDevelopmentOnlyChangeLater123456789