spring.application.name=demo-order-service
server.port=8082

payment.service.url=${PAYMENT_SERVICE_URL:http://localhost:8083}
inventory.service.url=${INVENTORY_SERVICE_URL:http://localhost:8084}
trace.ingestion.url=${TRACE_INGESTION_URL:http://localhost:8085}