spring.application.name=alert-service
server.port=8088

spring.datasource.url=jdbc:postgresql://localhost:5432/tracenet_trace_db
spring.datasource.username=ivanbhargava
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info